name: Run Gitleaks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  gosec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@master

